### ISSUE TITLE
Any help with this error?

### ISSUE THREAD

**Issue by TheSunKingXIV** [Sorrow446/Qo-DL#118]
Failed to check for update.

Traceback (most recent call last):
  File "Qo-DL.py", line 780, in <module>
  File "Qo-DL.py", line 607, in init
  File "Qo-DL.py", line 438, in update
UnboundLocalError: local variable 'latestVer' referenced before assignment

An exception has occurred. Press enter to exit.

**Comment by Koatohee** [comment]
Had the same error. Just wanted to download a single.

**Comment by DashLt** [comment]
Disable checking for updates in the config file.
