### ISSUE TITLE
Another exception occured

### ISSUE THREAD

**Issue by janhjanh** [Sorrow446/Qo-DL#27]
hello again and thanks for implementing my previous issue.

With the new windows version i get this:

Traceback (most recent call last):
  File "Qo-DL.py", line 38, in getConfig
  File "configparser.py", line 1233, in __getitem__
KeyError: 'checkForUpdates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Qo-DL.py", line 901, in <module>
  File "Qo-DL.py", line 530, in init
  File "Qo-DL.py", line 43, in getConfig
NameError: name 'msList2' is not defined
[11640] Failed to execute script Qo-DL

**Comment by Sorrow446** [comment]
Please grab the new config file template. Sorry for the changes, but it needed cleaning up a bit.
