### ISSUE TITLE
Download error while album name with '...' 

### ISSUE THREAD

**Issue by gmfit** [Sorrow446/Qo-DL#34]
Album link : https://play.qobuz.com/album/w20jtiwhagjzb

platform: windows & linux 

Error message:

Paul Watkins - Finzi : Cello Concerto, Eclogue...

Downloading track 1 of 6: I. Allegro moderato - 24-bit / 96 kHz FLAC  100%
Traceback (most recent call last):
  File "shutil.py", line 544, in move
FileNotFoundError: [WinError 3] The system cannot find the path specified: '1.flac' -> 'Qo-DL Downloads\\Paul Watkins - Finzi - Cello Concerto, Eclogue...\\1.flac'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Qo-DL.py", line 718, in <module>
  File "Qo-DL.py", line 689, in rip
  File "Qo-DL.py", line 606, in add_flac_cover
  File "shutil.py", line 558, in move
  File "shutil.py", line 257, in copy2
  File "shutil.py", line 121, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'Qo-DL Downloads\\Paul Watkins - Finzi - Cello Concerto, Eclogue...\\1.flac'
[136] Failed to execute script Qo-DL

**Comment by DashLt** [comment]
I believe this is fixed (in other words, it works on my machine), please use the newest version. Until there is a compiled release, follow the instructions [here](https://github.com/Sorrow446/Qo-DL/issues/45#issuecomment-509017646). Please report back to see if this has been resolved.

**Comment by DashLt** [comment]
Fixed.
