### ISSUE TITLE
crashes, no userAuth

### ISSUE THREAD

**Issue by OnepunchyMen** [Sorrow446/Qo-DL#47]
i always get this error message

UserAuthToken field in config file is empty. Fetching it...
Traceback (most recent call last):
	File "Qo-DL.py", line 901, in <module>
	File "Qo-DL.py", line 614, in init
	File "Qo-DL.py", line 54, in get_uat
NameError: name 'email' is not defined
[11188] Failed to execute script Qo-DL

**Comment by Sorrow446** [comment]
Known issue with r5a. Use r5 for now.

**Comment by OnepunchyMen** [comment]
Can you link me to it. Thanks man for your work

**Comment by OnepunchyMen** [comment]
thanks man it works :) but some tracks are area restricted anyways thanks a lot.
