### ISSUE TITLE
Complete refactor.

### ISSUE THREAD

**Issue by Sorrow446** [Sorrow446/Qo-DL#49]
The code is a mess as it is now. Split up and add more funcs.

**Comment by KGB-USSR** [comment]
This doesn't work for me. Log:
Traceback (most recent call last):
  File "C:\Qo\Qo-DL.py", line 932, in <module>
    init()
  File "C:\Qo\Qo-DL.py", line 883, in init
    trnumtg, trtotaltg, trtotal2tg, trarttmp)
  File "C:\Qo\Qo-DL.py", line 253, in rip
    print(f"Track {curtr} is restricted by right holders. Can't download.")
NameError: name 'curtr' is not defined

**Comment by jimsaye** [comment]
i have the same issue on ubuntu

**Comment by TitouanGendron** [comment]
Same issue on Debian, but it works well on windows...
The problem seems to come from the resquest signature of the POST 
`	responset = session.post("https://www.qobuz.com/api.json/0.2/track/getFileUrl?",
			params={
				"request_ts": timeunx,
				"request_sig": reqsigt,#reqsighst,
				"track_id": trackid,
				"format_id": formatId,
				"intent": "stream"
			}
		)
	tr = responset.json()
	print(tr)`
returns 
`{'status': 'error', 'code': 400, 'message': 'Invalid Request Signature parameter (1501ff69d99cf120c35dbc1d72719578)'}`
the request signature is MD5 hashed, before hash it was 
`	reqsigt = f"trackgetFileUrlformat_id{formatId}intentstreamtrack_id{trackid}{timeunx}0e47db7842364064b7019225eb19f5d2"
	print(reqsigt)`
gives
`trackgetFileUrlformat_id27intentstreamtrack_id5009409815626820040e47db7842364064b7019225eb19f5d2`

I didn't find any information about how the request must be, and I a not an expert with internet requests and all that stuff but I hope these results may help you to make it work on Linux!

Thanks for the amazing work!
