### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by 0OOOOOOO0** [Sorrow446/Qo-DL#67]
The Qo-DL.py script works correctly but as soon as i put N in "ALBUMARTIST" , "COPYRIGHT", "TRACKNUMBER" and "TRACKTOTAL" it stops working.

> The API did not return a(n) Composer. Tag will be left empty.
Traceback (most recent call last):
  File "C:\Program Files\Qo-DL\Qo-DL.py", line 717, in <module>
    init()
  File "C:\Program Files\Qo-DL\Qo-DL.py", line 699, in init
    rip(album_id, isTrack, session, comment, formatId, alcovs, downloadDir, fp,
keepCover)
  File "C:\Program Files\Qo-DL\Qo-DL.py", line 237, in rip
    for field in metadata:
RuntimeError: dictionary changed size during iteration

**Comment by 0OOOOOOO0** [comment]
"ALBUMARTIST" and "COPYRIGHT" allows me to deactivate it but what does not allow me to deactivate is "TRACKTOTAL" and "TRACKNUMBER".

**Comment by 0OOOOOOO0** [comment]
@DashLt 

"ALBUMARTIST" and "COPYRIGHT" allows me to deactivate it but what does not allow me to deactivate is "TRACKTOTAL" and "TRACKNUMBER".
