### ISSUE TITLE
cant download individual songs/track

### ISSUE THREAD

**Issue by OnepunchyMen** [Sorrow446/Qo-DL#77]
downloading album is ok even the display is like backspacing/eating back all the letters. but when i download single/individual track link i got an error.

Traceback (most recent call last):
	File "Qo-DL.py", line 784, in <module>
	File "Qo-DL.py", line 686, in init
	File "Qo-DL.py", line 155, in rip
KeyError: 'version'
[9548] Failed to execute script Qo-DL

**Comment by DashLt** [comment]
This has been fixed in the latest version of the .py file, and will be compiled in Qo-DL 5d.
