### ISSUE TITLE
Mac release

### ISSUE THREAD

**Issue by LordEchos** [Sorrow446/Qo-DL#89]
https://github.com/Sorrow446/Qo-DL/releases
5d doesn't include a Mac version. Will this be released?

The earlier version (from 3 months ago) gets me:

_./Qo-DL_x64_Mac_
_The following required fields in your config file are missing: app_id, app_secret, email, format_id, password, user_auth_token, naming_scheme, cover_size, move_to, keep_cover, use_proxy, skip_pw_hash_check, embed_cover, proxy, artist, label, performer, track, date, totaltracks.
Traceback (most recent call last):
  File "/Users/user/Desktop/Qo-DL.py", line 82, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1193, in set
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 901, in set
configparser.NoSectionError: No section: 'Config'_

Thanks for the effort.

**Comment by Sorrow446** [comment]
Should have both x64 & x86 builds up tomorrow.
